name = "resume-tracker"
main = "src/index.js"
compatibility_date = "2024-04-01"
account_id = "8bae875f3ce3f27b8a87b1e8f65edebe"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "RESUME_KV"
id = "6d4072ac67424c658af1fa88a555b8c5"
