name = "referral-tracker"
main = "src/index.js"
compatibility_date = "2024-04-01"
account_id = "8bae875f3ce3f27b8a87b1e8f65edebe"

observability.logs.enabled = true

# Default (dev) settings
route = "track-dev.nolanwelch.com/*"
kv_namespaces = [
    { binding = "REFERRAL_KV", id = "05a4a41bfe3c4f80ad716a7955529820" },
]


# -----------------------------
# Production Settings
# -----------------------------
[env.production]

route = "track.nolanwelch.com/*"

kv_namespaces = [
    { binding = "REFERRAL_KV", id = "2ecb5a80759144ebb3718f63c9274d60" },
]
