# These values are dynamically injected in GitHub Actions:
# - ACCOUNT_ID
# - DOMAIN
# - ZONE_ID
# - KV_PROD_ID

name = "referral-tracker"
main = "src/index.js"
compatibility_date = "2024-04-01"
account_id = "ACCOUNT_ID"

observability.logs.enabled = true

kv_namespaces = [{ binding = "REFERRAL_KV", id = "KV_PROD_ID" }]
