name: Deploy Worker

on:
  push:
    paths:
      - "workers/**" # Only redeploy if something in the workers folder changes
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy Worker
        run: |
          cd workers
          wrangler deploy --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
