name: Terraform Infra

on:
  push:
    paths:
      - "terraform/**"
      - "workers/**"
      - ".github/workflows/deploy.yml"
    branches:
      - main

  workflow_dispatch: # allow manual running of this Action

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      TF_VAR_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      TF_VAR_domain: ${{ vars.DOMAIN }}
      TF_VAR_pages_domain: ${{ vars.PAGES_DOMAIN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
